export { default as Footer} from "./Footer/Footer";
export { default as Header } from  "./Header/Header";
export { default as Navbar } from "./Navbar/navbar";
export { default as Subscribe } from "./Subscribe/Subscribe";
export { default as Content } from "./Landing/Content";
export { default as Features } from "./Features/Feature";
export { default as ApplyContent } from "./Apply/ApplyContent";
export { default as Layout } from "./Layout/SPlayout";
export { default as Circle } from "./Layout/SPcircle";
export { default as DevCards } from "./Learnable/devcards/Cards";
export { default as DesCards } from "./Learnable/descards/Cards";
export { default as Linkcontent } from "./Learnable/linkcontent";
export { default as Onecontent } from "./Learnable/onecontent";
export { default as Twocontent } from "./Learnable/twocontent";
export { default as Brands } from "./Brands/Brands";